import Head from "next/head";

const Layout = ({ children, page }) => {
  return (
    <div>
      <Head>
        <title>My Shop Guitar - {page}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Dede Layout</h1>
      {children}
    </div>
  );
};

export default Layout;
